users :
  path : /users/users.xml
path: /users
# Path to edit a user, name will be add as first indexed arg
edit: /sylma/modules/users/edit
profil: profil.xml
cookies:
  name: sylma-user
  # (!) This value should be rewrited for a good cookie security
  secret-key: This value is not really secret
  lifetime:
    # 8h
    short: 28800
    # ~7j
    normal: 403200
  remember :
    name : sylma-remember
    lifetime : 4032000
session:
  name: sylma-user
  lifetime: 28800
classes :
  @sylma-classbase : \sylma\core\user
  user :
    name : Basic
  cookie :
    name : Cookie
  redirect :
    \sylma\core\Redirect